//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommunicationDataLibrary.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECommunicationEntities : DbContext
    {
        public ECommunicationEntities()
            : base("name=ECommunicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Mailbox> Mailboxes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UserMailbox> UserMailboxes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetAllUser_Result> GetAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUser_Result>("GetAllUser");
        }
    
        public virtual ObjectResult<GetMailboxesUserWise_Result> GetMailboxesUserWise(Nullable<long> userMailboxId)
        {
            var userMailboxIdParameter = userMailboxId.HasValue ?
                new ObjectParameter("UserMailboxId", userMailboxId) :
                new ObjectParameter("UserMailboxId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMailboxesUserWise_Result>("GetMailboxesUserWise", userMailboxIdParameter);
        }
    
        public virtual ObjectResult<GetUserMailboxes_Result> GetUserMailboxes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserMailboxes_Result>("GetUserMailboxes");
        }
    }
}
