//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommunicationDataLibrary.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMailbox
    {
        public long UserMailboxId { get; set; }
        public Nullable<long> MailboxId { get; set; }
        public long UserId { get; set; }
        public bool IsMainContact { get; set; }
        public bool IsDefaultMailbox { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    }
}
